blob.server.port: 6124
taskmanager.memory.process.size: 1728m
logger.kafka.level: INFO
jobmanager.rpc.address: jobmanager
web.cancel.enable: true
jobmanager.memory.process.size: 1600m
jobmanager.rpc.port: 6123
query.server.port: 6125
logger.akka.level: INFO
logger.hadoop.level: WARN
rootLogger.level: INFO
parallelism.default: 1
taskmanager.numberOfTaskSlots: 4
web.submit.enable: true
logger.zookeeper.level: INFO
state.checkpoints.dir: s3://checkpoints/
