blob.server.port: 6124
taskmanager.memory.process.size: 1728m
logger.kafka.level: INFO
jobmanager.rpc.address: jobmanager
web.cancel.enable: true
jobmanager.memory.process.size: 1600m
jobmanager.rpc.port: 6123
query.server.port: 6125
logger.akka.level: INFO
logger.hadoop.level: WARN
rootLogger.level: INFO
parallelism.default: 1
taskmanager.numberOfTaskSlots: 4
web.submit.enable: true
logger.zookeeper.level: INFO
# checkpointing configurations
state.backend: filesystem
state.checkpoints.dir: s3a://checkpoints/flink/
state.backend.fs.checkpointdir: s3a://checkpoints/flink/
s3.access-key: admin
s3.secret-key: rootpass123
s3.endpoint: http://minio:9000
s3.path.style.access: true
